{"name": "TC010_Login with invalid credentials", "status": "passed", "description": "D:\\Project\\QE_JavaPython\\framework_python\\test_py_web\\tests\\test_cases\\..\\features\\sauce_demo.feature: TC010_Login with invalid credentials", "steps": [{"name": "Login into sauce demo using id and password", "status": "passed", "start": 1723446838692, "stop": 1723446838870}, {"name": "Click login button", "status": "passed", "start": 1723446841875, "stop": 1723446841964}, {"name": "Get error message after login failure", "status": "passed", "start": 1723446844965, "stop": 1723446845003}], "attachments": [{"name": "log", "source": "51461db4-583a-425d-9f4a-e4475aaa682a-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "95086299-400d-4b2f-94a9-834b096f16ee-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "_pytest_bdd_example", "value": "{'username': 'uuid_base32hb', 'pwd': 'c2VjcmV0X3NhdWNl'}"}], "start": 1723446828689, "stop": 1723446845003, "uuid": "9330cdf0-7ef9-4193-b683-6986bd3edd1f", "historyId": "6d1ebb14dab67d935cbe1b533f9c36cc", "testCaseId": "f376bf8030f727c3a79ad66993d326d4", "fullName": "tests.test_cases.test_saucedemo#test_report_tc10", "labels": [{"name": "severity", "value": "blocker"}, {"name": "feature", "value": "Validate Login Credentials"}, {"name": "tag", "value": "@pytest.mark.usefixtures"}, {"name": "parentSuite", "value": "tests.test_cases"}, {"name": "suite", "value": "test_saucedemo"}, {"name": "host", "value": "TIGER04836"}, {"name": "thread", "value": "24268-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_cases.test_saucedemo"}]}